# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - build
  - test

cache:
  paths:
    - /root/.m2/repository

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

java-build:
  #  variables:
  #    RUNNER_SCRIPT_TIMEOUT: 1h
  image: 
    name: mustangxu/maven:3.9-eclipse-temurin-23-1.0.0
    pull_policy: if-not-present
  stage: build
  script:
    #- cp /root/.m2/settings.xml .m2/
    - mvn -DskipTests clean package
  artifacts:
    paths:
      - java-playground/target/*.jar
