useCache: true

server:
  port: 8000
debug: false

spring:
  output:
    ansi:
      enabled: always
  application:
    name: Jay's Java Playground
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

#  datasource:
    #url: jdbc:mysql://10.163.113.121/playground
#    url: jdbc:mysql://127.0.0.1/playground
#    url: jdbc:h2:~/h2/playground
#    url: jdbc:postgresql://host.docker.internal/xujiajing
    #url:  jdbc:hsqldb:${user.home}/hsqldb/playground
#    hikari:
#      username: demo
#      password: demo

  jpa:
    #generate-ddl: true
    show-sql: false
#    hibernate:
#      ddl-auto: update
    open-in-view: false
    properties:
#      hibernate:
        #generate_statistics: ${useCache}
#        cache:
#          use_second_level_cache: ${useCache}
#          use_query_cache: ${useCache}
#          region:
#            factory_class: org.redisson.hibernate.RedissonRegionFactory
#              factory_class: jcache
#          redisson:
#            fallback: true
#            config: redisson.yaml
      eclipselink:
        cache.query-results: ${useCache}
        ddl-generation: create-or-extend-tables
#        logging.level: ALL
#      jakarta:
#        persistence:
#          sharedCache:
#            mode: ENABLE_SELECTIVE
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yaml
        
  jackson:
    serialization:
      fail-on-empty-beans: false

  boot:
    admin:
      client:
        url:
        - http://127.0.0.1:9000
        
  cloud:
    openfeign:
      okhttp:
        enabled: true
      compression:
        request:
          enabled: true
        response:
          enabled: true
      circuitbreaker:
        enabled: true
      micrometer:
        enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
#      hibernate.cache: debug
#      springframework:
#        web.reactive: debug

springdoc:
  swagger-ui:
    display-request-duration: true
    enabled: true
#    path: /swagger.html
    csrf:
      enabled: true
#  show-actuator: true
  
eureka:
  client:
    enabled: false
    healthcheck:
      enabled: true
#    service-url: 
#      defaultZone: http://127.0.0.1:${server.port}/eureka/

ribbon:
  eureka:
    enabled: true

#---
#spring:
#  config:
#    activate:
#      on-profile: [prod, dev]
#
#  datasource:
#    #url: jdbc:mysql://10.163.113.121/playground
#    #    url: jdbc:mysql://127.0.0.1/playground
#    url: jdbc:postgresql://host.docker.internal/xujiajing
#
---
useCache: false
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:shardingsphere:classpath:sharding-test.yaml
  
  shardingsphere:
    props:
      sql-show: true
    mode:
      type: Standalone
            
    datasource:
      names: ds_1, ds_2
      ds_1:
        type: com.zaxxer.hikari.HikariDataSource
        jdbcUrl: jdbc:h2:mem:db1
      ds_2:
        type: com.zaxxer.hikari.HikariDataSource
        jdbcUrl: jdbc:h2:mem:db2

  boot:
    admin:
      client:
        enabled: false

springdoc:
  swagger-ui:
    enabled: false

management:
  endpoint:
    health:
      enabled: false
  endpoints:
    enabled-by-default: false
