server:
  port: 8000

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    #url: jdbc:mysql://10.163.113.121/playground
#    url: jdbc:mysql://127.0.0.1/playground
#    url: jdbc:h2:~/h2/playground
    url: jdbc:postgresql://host.docker.internal/xujiajing
    hikari:
      username: xujiajing
      password: xujiajing
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
#      hibernate:
#        generate_statistics: true
#        cache:
#          use_second_level_cache: true
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE

#  boot:
#    admin:
#      client:
#        url:
#        - http://127.0.0.1:9000

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
#      hibernate.cache: debug
      springframework:
#        web.reactive: debug

springdoc:
  swagger-ui:
    enabled: true