server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://10.163.113.121/playground
#    url: jdbc:h2:~/h2/playground
    hikari:
      username: demo
      password: xujiajing
  jpa:
    generate-ddl: true
    show-sql: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
        - "*"