server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://172.16.2.50/playground
#    url: jdbc:h2:~/h2/playground
    hikari:
      username: demo
      password: xujiajing
  jpa:
    generate-ddl: true
    show-sql: true
