server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/playground
#    url: jdbc:h2:~/h2/playground
    hikari:
      username: root
      password: xujiajing
  jpa:
    generate-ddl: true
    show-sql: true