version: "3.9"
services:
  playground:
    build: .
    ports:
      - "8001:8000"
    environment:
      - "SW_AGENT_COLLECTOR_BACKEND_SERVICES=skywalking-oap:11800"
      - "SW_AGENT_INSTANCE_NAME=docker"
    depends_on:
      - skywalking-oap
#    links:
#      - skywalking-oap
  skywalking-oap:
    image: "apache/skywalking-oap-server"
    ports:
      - "12800:12800"
      - "11800:11800"
      - "1234:1234"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    environment:
      - "SW_STORAGE=postgresql"
      - "SW_DATA_SOURCE_USER=xujiajing"
      - "SW_DATA_SOURCE_PASSWORD=xujiajing"
      - "SW_JDBC_URL=jdbc:postgresql://host.docker.internal:5432/skywalking"
    volumes:
      - "playground:/skywalking"
  skywalking-ui:
    image: "apache/skywalking-ui"
    ports:
      - "9000:8080"
    depends_on:
      - skywalking-oap
    environment:
      - "SW_OAP_ADDRESS=http://skywalking-oap:12800"
volumes:
  playground:
