#FROM apache/skywalking-base
FROM bellsoft/liberica-openjre-alpine-musl:17
WORKDIR /app
EXPOSE 8000
COPY target/java-playground-1.0-SNAPSHOT.jar app.jar
ADD docker/skywalking /skywalking
VOLUME [ "/skywalking" ]
ENTRYPOINT ["java","-Xmx1G","--enable-preview",\
    "-XX:+UnlockExperimentalVMOptions","-XX:+UseZGC",\
    "-javaagent:/skywalking/agent/skywalking-agent.jar","-jar","/app/app.jar"]
